name: Marge-Build
on: push

jobs:
  build-marge:
    name: Build Marge Dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Node 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: npm
          
      - name: Install Deps
        run: npm ci
        
      - name: Build
        run: npm run build
      
